version: '3.9'

services:
    web:
        build: .
        container_name: "django"
        command: python /code/stepik_2/manage.py runserver 0.0.0.0:8000
        volumes:
        - .:/code
        ports:
        - 8000:8000
        env_file:
            - .env
